"""
Business chatbot.

Security design:
- We do NOT execute arbitrary SQL generated by the user.
- We map a small set of natural-language intents to predefined SQL queries.
- Optional Gemini is used only to summarize already-retrieved facts.
This is much safer than giving an LLM unrestricted database access.
"""

import os
import json
import pandas as pd
from dotenv import load_dotenv

try:
    from database import query_dataframe
except ImportError:
    from src.database import query_dataframe

load_dotenv()


def retrieve_business_context(question: str) -> dict:
    """Convert a natural-language question into safe, predefined analytics."""
    q = question.lower()

    if any(word in q for word in ["churn", "risk", "leaving", "retention"]):
        df = query_dataframe("""
            SELECT
                COUNT(*) AS customers,
                SUM(CASE WHEN future_orders = 0 THEN 1 ELSE 0 END) AS churned,
                AVG(days_since_last_purchase) AS avg_days_since_purchase
            FROM (
                SELECT
                    c.customer_id,
                    CAST(julianday('2024-06-30') - julianday(MAX(o.order_purchase_date)) AS INTEGER)
                        AS days_since_last_purchase,
                    COUNT(
                        CASE WHEN o.order_purchase_date > '2024-06-30'
                             AND o.order_purchase_date <= '2025-06-30'
                             THEN 1 END
                    ) AS future_orders
                FROM dim_customers c
                JOIN fact_orders o ON c.customer_id = o.customer_id
                WHERE o.order_status = 'delivered'
                GROUP BY c.customer_id
            )
        """)
        return {"intent": "churn", "data": df.to_dict("records")}

    if any(word in q for word in ["sales", "revenue", "category", "product"]):
        df = query_dataframe("""
            SELECT
                p.product_category,
                ROUND(SUM(o.price * o.quantity + o.freight_value), 2) AS revenue,
                COUNT(*) AS orders
            FROM fact_orders o
            JOIN dim_products p ON o.product_id = p.product_id
            WHERE o.order_status = 'delivered'
            GROUP BY p.product_category
            ORDER BY revenue DESC
            LIMIT 10
        """)
        return {"intent": "sales", "data": df.to_dict("records")}

    if any(word in q for word in ["review", "sentiment", "feedback", "complaint"]):
        df = query_dataframe("""
            SELECT
                ROUND(AVG(review_score), 2) AS average_review_score,
                COUNT(*) AS review_count,
                SUM(CASE WHEN review_score <= 2 THEN 1 ELSE 0 END) AS negative_reviews
            FROM dim_reviews
        """)
        return {"intent": "reviews", "data": df.to_dict("records")}

    if any(word in q for word in ["ltv", "lifetime", "customer value", "spend"]):
        path = os.path.join(
            os.path.dirname(os.path.dirname(__file__)),
            "reports",
            "customer_features.csv",
        )
        df = pd.read_csv(path)
        return {
            "intent": "ltv",
            "data": [{
                "customers": int(len(df)),
                "historical_spend_mean": float(df["total_spend"].mean()),
                "future_spend_mean": float(df["future_12m_spend"].mean()),
                "future_spend_median": float(df["future_12m_spend"].median()),
            }],
        }

    # A general safe overview.
    df = query_dataframe("""
        SELECT
            COUNT(*) AS orders,
            ROUND(SUM(price * quantity + freight_value), 2) AS revenue,
            COUNT(DISTINCT customer_id) AS customers
        FROM fact_orders
        WHERE order_status = 'delivered'
    """)
    return {"intent": "overview", "data": df.to_dict("records")}


def local_answer(context: dict) -> str:
    """Produce a deterministic answer without an external API."""
    intent = context["intent"]
    row = context["data"][0] if context["data"] else {}

    if intent == "churn":
        return (
            f"There are {row.get('customers', 0):,} modeled customers. "
            f"{row.get('churned', 0):,} have no delivered purchase in the future period "
            f"used by this demo. Average historical recency is "
            f"{row.get('avg_days_since_purchase', 0):.1f} days."
        )

    if intent == "reviews":
        return (
            f"The average review score is {row.get('average_review_score', 0):.2f}/5 "
            f"across {row.get('review_count', 0):,} reviews. "
            f"{row.get('negative_reviews', 0):,} reviews are rated 1–2."
        )

    if intent == "ltv":
        return (
            f"Historical average customer spend is "
            f"{row.get('historical_spend_mean', 0):.2f}. "
            f"Average future 12-month spend in the evaluation data is "
            f"{row.get('future_spend_mean', 0):.2f}."
        )

    if intent == "sales":
        top = context["data"][:3]
        lines = [
            f"{item['product_category']}: {item['revenue']:,.2f} revenue "
            f"from {item['orders']:,} orders."
            for item in top
        ]
        return "Top categories by revenue:\\n" + "\\n".join(lines)

    return (
        f"Delivered orders: {row.get('orders', 0):,}. "
        f"Revenue: {row.get('revenue', 0):,.2f}. "
        f"Customers: {row.get('customers', 0):,}."
    )


def gemini_answer(question: str, context: dict) -> str | None:
    """
    Optional Gemini integration.

    The LLM receives only retrieved facts, not unrestricted database access.
    If the API is missing or unavailable, return None.
    """
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        return None

    try:
        import google.generativeai as genai

        genai.configure(api_key=api_key)
        model = genai.GenerativeModel("gemini-1.5-flash")

        prompt = f"""
You are a business intelligence assistant.
Answer the user's question using ONLY the structured facts below.
Do not invent numbers or claims. If the facts do not answer the question,
say that the available data is insufficient.

User question:
{question}

Retrieved facts:
{json.dumps(context, indent=2)}

Keep the answer concise and business-focused.
"""
        response = model.generate_content(prompt)
        return response.text
    except Exception:
        return None


def answer_question(question: str) -> str:
    """Main chatbot entry point."""
    context = retrieve_business_context(question)

    llm_response = gemini_answer(question, context)
    if llm_response:
        return llm_response

    return local_answer(context)
