@echo off
echo Step 1: Creating demo data...
python src\generate_demo_data.py

echo Step 2: Loading SQLite database...
python src\ingest.py

echo Step 3: Training ML models...
python src\train_ml.py

echo Step 4: Training PyTorch model...
python src\train_dl.py

echo Step 5: Starting Streamlit...
streamlit run app\streamlit_app.py
pause
